config/routes.rb
Rails.application.routes.draw do
  root "posts#index"
  devise_for :users
  resources :posts do
    resources :comments, :like_posts
  end
  resources :users, only: [:show, :edit, :update]
  resources :friendships, only: [:create, :update, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable

  has_many :posts

  has_many :comments
  has_many :post_comments, through: :comments, class_name: :Post

  has_many :like_posts
  has_many :post_likes, through: :like_posts, class_name: :Post

  has_many :send_friendships, class_name: :Friendship,
    foreign_key: :user_id, dependent: :destroy

  has_many :receive_friendships, class_name: :Friendship,
    foreign_key: :friend_id, dependent: :destroy

  has_many :friends, through: :send_friendships, source: :friend_id
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :edit, :update, :post_owner?]

  def show
    @created_posts = @user.posts
    @like_posts = @user.like_posts
  end

  def edit
  end

  def update
    if @user.update_attributes edit_user_params
      flash[:success] = t ".profile_updated"
      redirect_to new_user_session_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit :email, :password,
      :password_confirmation
  end

  def edit_user_params
    params.require(:user).permit :email, :password,
      :password_confirmation
  end

  def find_user
    @user = User.find_by id: params[:id]
    return if @user
    redirect_to root_path
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user? user
    user == current_user
  end

  def post_owner?
    @user == current_user
  end
end

app/views/users/_created_post.html.erb
<% @created_posts.each do |post| %>
  <div class="row">
    <%= link_to post.title, post %><br>
    <% if post_owner? %>
      <%= link_to "Edit this blog", edit_post_path(post) %>
    <% end %>
  </div>
  <hr>
<% end %>

app/views/users/edit.html.erb
<div class="edit-form event-index">
  <h1 class="text-center"><%= t".heading" %></h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for @user do |f| %>
        <%= f.label :email, class: "form-label" %>
        <%= f.email_field :email, class: "form-input"  %>

        <%= f.label :password, class: "form-label" %>
        <%= f.password_field :password, class: "form-input"  %>

        <%= f.label :password_confirmation, class: "form-label"%>
        <%= f.password_field :password_confirmation, class: "form-input"  %>

        <%= f.submit t(".save_changes")%>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container user-profile">
  <div class="row">
    <aside class="col-md-3">
      <section>
        <p><b>Email:</b> <%= @user.email %></p>
        <p><%= link_to "Edit Profile", edit_user_path(current_user) %></p>
        <div class="relation row">
          <div class="col-lg-6">
            <%= link_to "Add Friend", friendships_path, remote: true %>
          </div>
          <div class="col-lg-6">
            <p>Cancel</p>
          </div>
        </div>
      </section>
    </aside>
    <div class="col-md-9 user-tab">
      <ul class="nav nav-tabs">
        <li class="active"><a data-toggle="tab" href="#friend">Friends</a></li>
        <li><a data-toggle="tab" href="#like">Blog liked</a></li>
        <li><a data-toggle="tab" href="#comment">Comments</a></li>
        <li><a data-toggle="tab" href="#create">Created Blogs</a></li>
      </ul>
      <div class="tab-content clearfix">
        <div id="friend" class="tab-pane fade in active">
        </div>
        <div id="like" class="tab-pane fade">
          <% if !@like_posts.empty? %>
            <% @like_posts.each do |like_post| %>
              <%= link_to like_post.post.title, like_post.post, class: "count-in-profile" %><br>
              <span>Like at</span> <%= like_post.created_at.strftime("%H:%M:%S %d/%m/%Y") %><br>
              <hr>
            <% end %>
          <% end %>
        </div>
        <div id="comment" class="tab-pane fade">
        </div>
        <div id="create" class="tab-pane fade">
          <%= render "created_post" %>
        </div>
      </div>
    </div>
  </div>
</div>