config/routes.rb
Rails.application.routes.draw do
  root "posts#index"
  devise_for :users
  resources :posts do
    resources :comments, :like_posts
  end
  resources :users, only: [:show, :edit, :update]
  resources :friendships, only: [:create, :update, :destroy]
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  has_many :comments
  has_many :user_comments, through: :comments, class_name: :User

  has_many :like_posts
  has_many :user_likes, through: :like_posts, class_name: :User

  validates :title, presence: true
  validates :body, presence: true
  validates :user_id, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update]
  def index
    @posts = Post.all.page(params[:page]).per(10)
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build post_params
    @post.user = current_user

    if @post.save
      flash.now[:success] = t :event_created
      redirect_to @post
    else
      flash[:danger] = @post.errors.full_messages
      redirect_to new_post_path
    end
  end

  def show
  end

  def edit
  end

  def update
    if @post.update_attributes post_params
      redirect_to @post
    else
      flash[:danger] = t :update_false
      render :edit
    end
  end

  private

  def find_post
    @post = Post.find_by id: params[:id]
    if @post.nil?
      flash[:danger] = t :error
      redirect_to root_url
    end
  end

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def like? post
    current_user.like_posts.find_by(post_id: post)
  end
end

app/views/posts/_post.html.erb
<div class="row">
  <div class="col-lg-12">
    <%= link_to post.title, post %>
  </div>
  <div class="col-lg-12">
    <p><%= post.created_at.strftime("%d-%m-%Y %H:%M") %></p>
  </div>
  <div class="col-lg-12">
    <p><%= post.body %></p>
  </div>
</div>
<hr>

app/views/posts/_post_list.html.erb
<div class="col-lg-8 col-lg-offset-2">
  <% @posts.each do |post| %>
    <%= render post %>
  <% end %>
</div>
<div class="row">
  <div class="col-lg-12 col-md-12 bottom-paginate">
    <%= paginate @posts %>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="container-fluid post-index">
  <div class="row new-post">
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 col-lg-offset-3 col-md-offset-3 col-sm-offset-3">
      <h1 class="form-title"><%= t ".heading" %></h1>
      <%= form_for @post do |f| %>
        <div class="form-label">
          <%= f.label :title, t(".name"), class: "form-label anchor", id: "form-name" %>
          <%= f.text_field :title, class: "form-input", placeholder: t(".post_name") %>
        </div>

        <div class="form-label">
          <%= f.label :body, t(".des"), class: "control-label anchor", id: "form-des" %>
          <%= f.text_area :body, id: "markdown", class: "form-control", cols: "40", rows: "10",
            placeholder: t(".post_des") %>
        </div>

        <div class="form-label">
          <div>
            <%= f.submit t(".save") %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container-fluid post-index">
  <div class="row">
    <%= render partial: "posts/post_list" %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container-fluid post-index">
  <div class="row new-post">
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 col-lg-offset-3 col-md-offset-3 col-sm-offset-3">
      <h1 class="form-title"><%= t ".heading" %></h1>
      <%= form_for @post do |f| %>
        <div class="form-label">
          <%= f.label :title, t(".name"), class: "form-label anchor", id: "form-name" %>
          <%= f.text_field :title, class: "form-input", placeholder: t(".post_name") %>
        </div>

        <div class="form-label">
          <%= f.label :body, t(".des"), class: "control-label anchor", id: "form-des" %>
          <%= f.text_area :body, id: "markdown", class: "form-control", cols: "40", rows: "10",
            placeholder: t(".post_des") %>
        </div>

        <div class="form-label">
          <div>
            <%= f.submit t(".sub"), class: "W2Gbutton" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="row">
  <div class="col-lg-8 col-lg-offset-2 blog-content">
    <div class="blog-title">
      <%= @post.title %>
    </div>
    <p>Created at: <%= @post.created_at.strftime("%d-%m-%Y %H:%M") %></p>
    <div class="post-owner">
      <%= link_to @post.user.email, user_path(@post.user) %>
    </div>
    <div class="markdown">
      <%= markdown @post.body %>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-lg-8 col-lg-offset-2">
    <% if user_signed_in? && like?(@post.id) %>
      <%= button_to post_like_posts_path(@post.id), remote: true, class: "clear" do %>
        <p class="count" id="like_count_<%= @post.id %>"><%= @post.like_posts.count %></p>
        <i class="fa fa-thumbs-o-up fa-thumbs-o-up-press" id="like_<%= @post.id %>" aria-hidden="true"></i>
      <% end %>
    <% else %>
      <%= button_to post_like_posts_path(@post.id), remote: true, class: "clear" do %>
        <p class="count" id="like_count_<%= @post.id %>"><%= @post.like_posts.count %></p>
        <i class="fa fa-thumbs-o-up" id="like_<%= @post.id %>" aria-hidden="true"></i>
      <% end %>
    <% end %>
  </div>
  <div class="col-lg-8 col-lg-offset-2">
    <hr>
  </div>
</div>
<div class="col-lg-8 col-lg-offset-2">
  <% if user_signed_in? %>
    <div class="comment-form well">
      <%= render "comments/form" %>
    </div>
  <% end %>
  <hr>
  <div class="showing-comments">
    <%= render @post.comments %>
  </div>
</div>